name: GitHub Actions Demo
on: [push]
jobs:
  logContributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -laR
      - uses: ./.github/actions/show-contributors
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/contributors
          owner: jaked
          repo: actions-experiment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"
